### ISSUE TITLE
How to test with HTTPS

### ISSUE THREAD

**Issue by jd-boyd** [MABelanger/react-html5-camera-photo#140]
I'm trying to work out how to change some behaviour in this library. I might file issues about what I want once I figure out more of what it should look like.

In the meantime, I want to test an mobile, and I'm having trouble with that.
I did `npm install` of head. I think did `npm start`, and that runs on localhost:3000,  which I can test on my desktop web browsers. However, this is without HTTPS, which means no testing this on Android/iOS.  If I instead run `HTTPS=true npm start`, I get this error in the terminal windows:
```
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
node:internal/buffer:961
    super(bufferOrLength, byteOffset, length);
    ^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (node:internal/buffer:961:5)
    at Handle.onStreamRead [as onread] (node:internal/stream_base_commons:189:19)
    at Stream.<anonymous> (/home/jdboyd/work/mvp/react-html5-camera-photo/node_modules/handle-thing/lib/handle.js:120:12)
    at Stream.emit (node:events:526:35)
    at endReadableNT (/home/jdboyd/work/mvp/react-html5-camera-photo/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.17.0
```

I apologize for not being an experience react  dev, so I may be missing something obvious. If there is an obvious step I should be doing for HTTP testing, it might be nice if that was added to the README.

**Comment by MABelanger** [comment]
Hi @jd-boyd, It's seem to be a nodejs version issue of the new release, we need to update component in packages.json to the last version. I will do that, Thank for reporting. If you rely you need to test right away, can use nvm to downgrade your nodejs version.
